version: '3.8'

services:
  kalilab:
    build: .
    container_name: kalilab
    ports:
      - "2223:22"      # SSH Port for Kali
      - "8081:8080"    # Code Server for Kali
    volumes:
      - ./mission_files:/home/kali/mission
    restart: unless-stopped
    tty: true
